import * as muicons from '@mui/icons-material'

export const logos = Object.freeze({
    generaltask_single_color: 'images/gt-logo-single-color.svg',
    generaltask_black_on_white: 'images/gt-logo-black-on-white.svg',
    generaltask: '/images/generaltask.svg',
    generaltask_beta_yellow: '/images/GT-beta-logo.png',
    generaltask_beta_blue: '/images/GT-beta-logo-blue.png',
    generaltask_yellow_circle: '/images/gt-logo-yellow-circle.png',
    generaltask_blue_circle: '/images/gt-logo-blue-circle.png',
    github: muicons['GitHub'],
    gmail: '/images/google.svg',
    gcal: '/images/gcal.png',
    google_meet: '/images/google-meet.svg',
    jira: '/images/jira.svg',
    linear: '/images/linear.png',
    slack: '/images/slack.svg',
})

export const icons = Object.freeze({
    arrow_ascend: muicons['ArrowCircleUp'],
    arrow_descend: muicons['ArrowCircleDown'],
    arrow_down: muicons['ArrowDownward'],
    arrow_left: muicons['ArrowBack'],
    arrow_right: muicons['ArrowForward'],
    arrow_up: muicons['ArrowUpward'],
    arrow_up_down: muicons['ImportExport'],
    arrows_in: muicons['CloseFullscreen'],
    arrows_out: muicons['OpenInFull'],
    arrows_repeat: muicons['Sync'],
    bold: muicons['FormatBold'],
    bolt: muicons['ElectricBolt'],
    calendar_blank: muicons['CalendarToday'],
    calendar_days: muicons['CalendarMonth'],
    calendar_pen: muicons['EditCalendar'],
    calendar_star: muicons['EventAvailable'],
    caret_down_solid: muicons['ArrowDropDownCircle'],
    caret_down: muicons['ArrowDropDown'],
    caret_left: muicons['ArrowLeft'],
    caret_right: muicons['ArrowRight'],
    caret_up: muicons['ArrowDropUp'],
    chartLineUp: muicons['ShowChart'],
    check_circle_wavy: muicons['Verified'],
    check: muicons['Check'],
    checkbox_checked_solid: muicons['CheckBox'],
    checkbox_checked: muicons['CheckBox'],
    checkbox_unchecked: muicons['CheckBoxOutlineBlank'],
    checkCircleSolid: muicons['CheckCircle'],
    clock: muicons['WatchLater'],
    clone: muicons['FileCopy'],
    code_block: muicons['IntegrationInstructions'],
    code: muicons['Code'],
    comment: muicons['Message'],
    copy: muicons['ContentCopy'],
    domino: muicons['DragIndicator'],
    dot: muicons['FiberManualRecord'],
    emptySet: muicons['HideSource'],
    ellipsisVertical: muicons['MoreVert'],
    exclamationTriangleSolid: muicons['Warning'],
    external_link: muicons['OpenInNew'],
    eye: muicons['Visibility'],
    eye_slash: muicons['VisibilityOff'],
    filter: muicons['FilterList'],
    fire: muicons['LocalFireDepartment'],
    flask: muicons['Science'],
    folder: muicons['Folder'],
    gcal: logos.gcal,
    gear: muicons['Settings'],
    github_high: '/images/github_high.svg',
    github_low: '/images/github_low.svg',
    github_med: '/images/github_med.svg',
    github_paused: '/images/github_paused.svg',
    github: logos.github,
    globe: muicons['Language'],
    hamburger: muicons['Menu'],
    headphones: muicons['Headphones'],
    houseDay: muicons['Home'],
    inbox: muicons['Inbox'],
    infinity: muicons['AllInclusive'],
    infoCircleSolid: muicons['Info'],
    italic: muicons['FormatItalic'],
    jira: logos.jira,
    label: muicons['LocalOffer'],
    linear: logos.linear,
    linear_cycle_all: '/images/linear_cycle_all.svg',
    linear_cycle_current: '/images/linear_cycle_current.svg',
    linear_cycle_next: '/images/linear_cycle_next.svg',
    linear_cycle_none: '/images/linear_backlog.svg',
    linear_cycle_previous: '/images/linear_cycle_previous.svg',
    link: muicons['Link'],
    link_slashed: muicons['LinkOff'],
    list_ol: muicons['FormatListNumbered'],
    list_ul: muicons['FormatListBulleted'],
    list: muicons['List'],
    magnifying_glass: muicons['Search'],
    megaphone: muicons['Campaign'],
    note: muicons['Note'],
    penToSquare: muicons['EditNote'],
    pencil: muicons['Mode'],
    play: muicons['PlayArrow'],
    plus: muicons['Add'],
    priority_high: muicons['KeyboardDoubleArrowUp'],
    priority_low: muicons['KeyboardDoubleArrowDown'],
    priority_medium: muicons['DragHandle'],
    priority_none: muicons['RemoveCircle'],
    priority_urgent: muicons['Whatshot'],
    priority: muicons['Whatshot'],
    quote_right: muicons['FormatQuote'],
    rankingStar: muicons['Leaderboard'],
    repository: muicons['Inventory'],
    save: muicons['Save'],
    share: muicons['Share'],
    sidebar: muicons['ViewSidebar'],
    sidebarFlipped: muicons['ViewSidebar'], //this needs to be changed
    slack: logos.slack,
    sort: muicons['Sort'],
    sortArrows: muicons['SwapVert'],
    spinner: muicons['Refresh'],
    strikethrough: muicons['StrikethroughS'],
    square: muicons['Square'],
    squarePlus: muicons['AddBox'],
    squareMinus: muicons['IndeterminateCheckBox'],
    subtask: muicons['AccountTree'],
    timer: muicons['Timer'],
    trash: muicons['Delete'],
    underline: muicons['FormatUnderlined'],
    user: muicons['Person'],
    users: muicons['Group'],
    video: muicons['Videocam'],
    warning: muicons['Error'],
    warningTriangle: muicons['Warning'],
    x: muicons['Close'],
})

export const buttons: { [key: string]: string } = {
    google_sign_in: '/images/google_sign_in.png', //missing svg
}

export const externalStatusIcons = Object.freeze({
    // Linear
    backlog: '/images/linear_backlog.svg',
    unstarted: '/images/linear_todo.svg',
    started: '/images/linear_inprogress.svg',
    completed: '/images/linear_done.svg',
    canceled: '/images/linear_canceled.svg',

    inreview: '/images/linear_inreview.svg',
    triage: '/images/linear_triage.svg',
    duplicate: '/images/linear_duplicate.svg',

    // Jira
    new: '/images/jira/new.svg',
    indeterminate: '/images/jira/indeterminate.svg',
    done: '/images/jira/done.svg',
})

export const focusModeBackground = '/images/focus_mode_background.jpg'
export const noteBackground = '/images/note_background.jpg'
export const checkBig = '/images/check_big.svg'

export type TLogoImage = keyof typeof logos
export type TIconImage = keyof typeof icons
export type TExternalStatusImage = keyof typeof externalStatusIcons
